---
# UI Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui
  namespace: s6arsene
  labels:
    app: ui
spec:
  project: default
  
  source:
    repoURL: https://github.com/Arsenet7/new-revive.git
    targetRevision: HEAD
    path: helm-revive/ui  # Path to UI helm chart
    
    helm:
      valueFiles:
        - values.yaml
      
      parameters:
        - name: image.tag
          value: latest
  
  destination:
    server: https://kubernetes.default.svc
    namespace: s6arsene
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s

---
# Catalog Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog
  namespace: s6arsene
  labels:
    app: catalog
spec:
  project: default
  
  source:
    repoURL: https://github.com/Arsenet7/new-revive.git
    targetRevision: HEAD
    path: helm-revive/catalog  # Path to Catalog helm chart
    
    helm:
      valueFiles:
        - values.yaml
      
      parameters:
        - name: image.tag
          value: latest
  
  destination:
    server: https://kubernetes.default.svc
    namespace: s6arsene
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s

---
# Assets Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: assets
  namespace: s6arsene
  labels:
    app: assets
spec:
  project: default
  
  source:
    repoURL: https://github.com/Arsenet7/new-revive.git
    targetRevision: HEAD
    path: helm-revive/assets  # Path to Assets helm chart
    
    helm:
      valueFiles:
        - values.yaml
      
      parameters:
        - name: image.tag
          value: latest
  
  destination:
    server: https://kubernetes.default.svc
    namespace: s6arsene
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s